name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fetch Submodules
      run: git submodule init && git submodule update
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mrmcscreamypant/glister-server:$(date +%s)
    - name: Push the Docker image
      run: docker push mrmcscreamypant/glister-server:tagname
